name: Snyk and Semgrep Scan

on:
  push:
    branches: [ "main" ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: p/default
    - name: Build Docker image
      run: docker build -t nannyapp:latest .
    - name: Run Snyk to check Docker image for vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: nannyapp:latest
        args: --file=Dockerfile
